name: Debug build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          # Raspberry Pi OS 64 bit
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            bin: get-LAN-IP-telegram-bot-rs
            command: build
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            bin: get-LAN-IP-telegram-bot-rs
            command: build
    name: ${{ matrix.platform.target }}
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.sha }}
      os: ${{ matrix.platform.os }}
      binary-mode: debug
      command: ${{ matrix.platform.command }}
      bin: ${{ matrix.platform.bin }}
      target: ${{ matrix.platform.target }}
      args: "--locked"
      strip: true
